### ISSUE TITLE
Unseen scribe and Requisition tome GUI crash

### ISSUE THREAD

**Issue by wazroz** [Tuhljin/Automagy#48]
When I open the GUI interface search for an item in the Unseen Scribe or Requisition tome, my Minecraft client crashes to the technic launcher. I am using Minecraft 1.7 my automagy version is 1.7.10-0.28.2. I play on a server with a lot of mods and even the modpack creator crashes when he uses my inventarium. I have the only inventarium on the server.

        at tuhljin.automagy.gui.GUIScribe.updateStacksDisplay(GUIScribe.java:237)
	at tuhljin.automagy.gui.GUIScribe.func_73863_a(GUIScribe.java:379)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Tuhljin** [comment]
That doesn't seem to be the full error message. What comes before "at tuhljin.automagy.gui.GUIScribe.updateStacksDisplay(GUIScribe.java:237)"?

This is probably caused by an item in one of the monitored inventories behaving unexpectedly. You could try to figure out which item it is by using the process of elimination, disconnecting containers from the system, adding/removing items, etc.

**Comment by wazroz** [comment]
http://pastebin.com/68keD2Q6

This is the the modpack creators error crash report. He gets the same error as I do when he looks into my inventarium.

**Comment by Tuhljin** [comment]
What this is telling me is that some mod you have adds an item that has a null value as part of its tooltip (or manipulates that return for another item). I could add a workaround for that, but I'd imagine that other problems could still arise from that broken tooltip.

**Comment by wazroz** [comment]
Okay, thanks for helping. I'll try removing items until I find the troublesome item.

**Comment by Tuhljin** [comment]
Please let me know what you find so I can try to replicate the issue and make sure my workaround... works.

**Comment by wazroz** [comment]
Okay, last night I got my inventarium setup and running at another location. And I slowly put in stuff and  checked my unseen scribe. Every time I placed items in the chests, the last items I threw in, crashed my client. So I took them out and looked into the inventarium, no crash. So just to make sure, I tossed the items I took out and no crash....I used the search to find the items and I was getting no crashes. Not knowing what was going on and I had work this morning, I went to bed. When I get out tonight I'll look at it further, cause I don't what mods the items were from. I'll also attach some screen shots for reference of my setup when I find something.

**Comment by wazroz** [comment]
#Update. After removing everything, but the magical crops seeds, unseen scribe still crashed still crashed. The item mod origins that were inside the inventarium. Ars Magica 2, Thaumcraft, Automagy, TInker's Construct, Magical Crops, and vanilla minecraft items. I do think that more I put in the faster the crash happens. Because with the Magical Crops I had thought I had removed the items causing the crash, but after like 10 minutes later looking in the Unseen Scribe, it had finally crashed. Where as if I had the chests connected to the Unseen scribe were full. I hope this is all helpful.

**Comment by wazroz** [comment]
Okay I put all of the items back into the chests connected to the inventarium and had no crash, I even checked item by item and no crash happened. So I assumed it may have fixed itself, but not more then like 3 minutes into getting with on what I was wanting to do, I crashed.

**Comment by Tuhljin** [comment]
So this is only with magic crops items? What kind of container are the problem items in?

**Comment by wazroz** [comment]
The items are in chests from the Gany's Surface mod. But I had them originally in vanilla minecraft chests and it was still crashing. It almost seems like the items are not the cause, but some random event that occurs. Like something has to be just right for it to crash. At first I assumed it may have been  a memory leak issue so I had up'd the RAM usage on minecraft to 6gbs and java at a later point to 2gbs, still that was not the case.

I know this may not be helpful, but at this point I have reached the extent to my knowledge of this. I'll continue testing, but I am not sure if I'll convince the modpack creator to remove mods to fix a single issue. (Also I know this is late observation, but I do not get the crash on a local game. It only crashes on the server.)

**Comment by wazroz** [comment]
I just tried my creative world and it crashed. So both server and local play crashes.

**Comment by Tuhljin** [comment]
I'll try to get an update out to fix this within the next few days.

**Comment by wazroz** [comment]
I will be anxiously waiting. Thank you.
