### ISSUE TITLE
Version Checker Failure

### ISSUE THREAD

**Issue by Shahelion** [Tuhljin/Automagy#70]
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://everburningtorch.com/minecraft/automagy/checkVersion/?v=0.28.2
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[12:01:00] [Automagy Version Checker Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tuhljin.automagy.lib.VersionCheckerThread.run(VersionCheckerThread.java:30)

**Comment by Tuhljin** [comment]
Does this cause any problems playing or is it just a debug message in the log in the separate window?

The website that handled version checking is having problems. I'm not able to fix it easily at the moment. You can disable version checking in the Automagy config file.
